# -*- coding: utf-8 -*-
"""TFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1utP9LnzA3MwN8i9WqTzhkvHjTrB5D4mN
"""

! nvidia-smi

!pip install pytorch-lightning pytorch-forecasting torchmetrics -q

# Colab 사용 시에만 셀 실행 & 계정 연결
from google.colab import drive
drive.mount('/content/drive')

import sys, torch, lightning, pytorch_forecasting as pf
print(sys.version)
print("torch", torch.__version__)
print("lightning", lightning.__version__)
print("forecasting", pf.__version__)
print("cuda runtime in wheel:", torch.version.cuda)
print("gpu available:", torch.cuda.is_available())

"""
Team 아쿠아리움 — Temporal Fusion Transformer (TFT) 최종 스크립트
"""
import os
import warnings
import pandas as pd
import numpy as np
import re
import torch
import lightning.pytorch as pl
from lightning.pytorch import Trainer, seed_everything
from lightning.pytorch.callbacks import EarlyStopping, ModelCheckpoint
from pytorch_forecasting import TimeSeriesDataSet
from pytorch_forecasting.data.encoders import GroupNormalizer
from sklearn.preprocessing import StandardScaler
from pytorch_forecasting.models import TemporalFusionTransformer
from pytorch_forecasting.metrics import QuantileLoss

warnings.filterwarnings('ignore')

# -------------------------------
# 1) 라이브러리 & 경로
# -------------------------------
# Colab 사용 시 구글 드라이브에 엑셀 파일 업로드하고, 경로 복사 및 붙여넣기
# Jupyter Notebook 사용 시 ipynb 파일의 위치와 같은 폴더에 엑셀 파일 넣고, 그냥 이름만 입력
PATH_TRAIN = '/content/drive/MyDrive/Colab Notebooks/아쿠아리움/2014_2020_train_full_interpolated_filled_lag_plus_with_elev_lags_with_sum24h.csv'
PATH_SITE = '/content/drive/MyDrive/Colab Notebooks/아쿠아리움/12개_지하수_지점_정보.csv'
PATH_TEST_INPUTS = '/content/drive/MyDrive/Colab Notebooks/아쿠아리움/2021_2023_시계열_지하수_기상_test_inputs_interpolated.csv'
PATH_TEST_SAMPLE = '/content/drive/MyDrive/Colab Notebooks/아쿠아리움/2021_2023_시계열_지하수_test_sample.csv'

OUTPUT_DIR = 'outputs'
CKPT_DIR = 'tft_checkpoints'
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(CKPT_DIR, exist_ok=True)

seed_everything(42, workers=True)

# -------------------------------
# 2) 유틸: 시간/지점 컬럼 표준화 -> ds는 날짜 및 시간 / series_id는 지점 / y는 지하수 수위(타겟)
# -------------------------------
def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    dt_cols = [c for c in df.columns if c.lower() in ['datetime','time','ymd','ymdh','date']]
    if not dt_cols:
        raise ValueError('datetime/ymd/ymdh/date 컬럼을 찾을 수 없습니다.')
    df.rename(columns={dt_cols[0]: 'ds'}, inplace=True)
    df['ds'] = pd.to_datetime(df['ds'])

    id_cols = [c for c in df.columns if c.lower() in ['code','code_new','site','site_id','station']]
    if not id_cols:
        raise ValueError('지점 식별자(code/site 등) 컬럼을 찾을 수 없습니다.')
    df.rename(columns={id_cols[0]: 'series_id'}, inplace=True)

    y_cols = [c for c in df.columns if c.lower() in ['elev','target','y']]
    if y_cols:
        df.rename(columns={y_cols[0]: 'y'}, inplace=True)
    return df

# -------------------------------
# 3) 데이터 로드 & 머지(정적 특성) -> 동적 정보인 시계열 데이터에 정적 정보 추가
# -------------------------------
train = pd.read_csv(PATH_TRAIN, encoding='cp949')
site = pd.read_csv(PATH_SITE, encoding='cp949')

for df in (train, site):
    df.columns = df.columns.str.replace('.', '_', regex=False)

train = normalize_columns(train)
site = site.copy()
site_id_cols = [c for c in site.columns if c.lower() in ['code','code_new','site','site_id','station']]
if not site_id_cols:
    raise ValueError('정적 지점 파일에서 식별자 컬럼을 찾을 수 없습니다.')
site.rename(columns={site_id_cols[0]: 'series_id'}, inplace=True)

static_cols = [c for c in site.columns if c != 'series_id']
train = train.merge(site, on='series_id', how='left')

# -------------------------------
# 4) 시간 인덱스 & 정렬
# -------------------------------
train = train.sort_values(['series_id', 'ds']).reset_index(drop=True)
train['time_idx'] = train.groupby('series_id').cumcount()

# -------------------------------
# 5) 변수 구성 -> 시간을 나타내는 hour, dow(day of week), month에 대한 변수 추가
# -------------------------------
reserved = {'y','series_id','ds','time_idx'} | set(static_cols)
all_feature_cols = [c for c in train.columns if c not in reserved]

train['hour'] = train['ds'].dt.hour
train['dow'] = train['ds'].dt.dayofweek
train['month'] = train['ds'].dt.month
known_future_real = ['hour','dow','month']

num_cols = [c for c in all_feature_cols if np.issubdtype(train[c].dtype, np.number)]
cat_cols = [c for c in all_feature_cols if c not in num_cols]

# -------------------------------
# 6) 학습/검증 분할 -> 현재 상태에서는 테스트를 위해 2014-2018 학습 & 2019-2020 검증(사실상의 테스트)으로 구분. 모델 완성 시 필요 없는 부분
# -------------------------------
FINAL_TRAIN = True  # >>> CHANGED: 최종 제출용이면 True

CUTOFF_DATE = pd.Timestamp('2018-12-31 23:00:00')
max_encoder_length = 168
max_prediction_length = 24

if FINAL_TRAIN:
    training_df = train.copy()         # >>> CHANGED: 2014–2020 전체 학습
    validation_df = None               # >>> CHANGED: 검증 사용 안함
else:
    training_df = train[train['ds'] <= CUTOFF_DATE].copy()
    validation_df = train[train['ds'] > CUTOFF_DATE].copy()

# train.info() -> 모델 실행 시 불필요

# 모델 실행 시 불필요
"""
# 5-1) 변수 구성에 대한 분석 -> y와의 상관관계 (y를 제외한 나머지 변수가 1이 나오면 안됨!)
print("모델에 입력되는 숫자형 시계열 피처 목록:")
print([c for c in num_cols if c not in static_cols])

# 각 숫자형 변수와 타겟(y) 간의 상관관계 확인
print("\n타겟(y)과의 상관관계:")
print(train[num_cols + ['y']].corr()['y'].sort_values(ascending=False))
"""

# -------------------------------
# 7) TimeSeriesDataSet 생성
# -------------------------------

# ★ 중요 ★
# 대회 규칙을 지키기 위해 지하수 수위에 대한 Lag를 t-168, 즉 7일 이전 데이터를 참조함 -> GPU 성능에 따라 참조할 값을 추가해도 됨! (ex: 7일전, 14일전, 21일전...)
# 'y' 대신 'elev_for_lag' 변수를 이용해 7일 전 데이터를 참조하도록 수정

# 스케일링할 모든 수치형 변수 리스트를 먼저 정의합니다.
# static_reals와 time_varying_unknown_reals를 합칩니다.
reals_to_scale = [c for c in static_cols if np.issubdtype(train[c].dtype, np.number)] + \
                 [c for c in num_cols if c not in static_cols]

# 기존 common_kwargs 딕셔너리 구조
common_kwargs = dict(
    time_idx='time_idx',
    target='y',
    group_ids=['series_id'],
    max_encoder_length=max_encoder_length,
    max_prediction_length=max_prediction_length,

    # ⭐️ 여기에 scalers 인자 추가! ⭐️
    # 위에서 정의한 reals_to_scale 리스트의 모든 변수에 StandardScaler를 적용
    scalers={col: StandardScaler() for col in reals_to_scale},

    static_categoricals=[c for c in static_cols if train[c].dtype == 'O'],
    static_reals=[c for c in static_cols if np.issubdtype(train[c].dtype, np.number)],
    time_varying_known_categoricals=[c for c in cat_cols if c not in static_cols],

    # known_future_real ('hour', 'dow', 'month')은 이미 범위가 작고 일정하므로 스케일링에서 제외합니다.
    time_varying_known_reals=known_future_real,

    time_varying_unknown_reals=[c for c in num_cols if c not in static_cols],

    target_normalizer=GroupNormalizer(
        groups=["series_id"], transformation="softplus"
    ),
    add_relative_time_idx=True,
    add_target_scales=True,
    add_encoder_length=True,
)

training = TimeSeriesDataSet(training_df, **common_kwargs)
if validation_df is not None:
    validation = TimeSeriesDataSet.from_dataset(training, validation_df, stop_randomization=True)
else:
    validation = None

batch_size = 256
train_loader = training.to_dataloader(train=True, batch_size=batch_size, num_workers=4)
val_loader = None if validation is None else validation.to_dataloader(train=False, batch_size=batch_size, num_workers=4)

# 모델 실행 시 불필요
"""
!pip install optuna -q
!pip install optuna-integration[pytorch_lightning]
"""

# 모델 실행 시 불필요
"""
# -------------------------------
# 8-1) Optuna — 영속화 + 타임박스 + 절약 탐색 → 최종 재학습
# -------------------------------
import os, json, time, gc
import optuna
from optuna.integration.pytorch_lightning import PyTorchLightningPruningCallback
from pytorch_lightning.loggers import CSVLogger
num_workers = 2
# ====== 탐색/재학습 예산 ======
SEARCH_TIMEOUT_MIN   = 300        # 탐색 총 시간 예산(분) — 세션 끊김 대비 타임박스
N_TRIALS_UPPER_BOUND = 100       # 시간 안에서 가능한 만큼만 시도
MAX_EPOCHS_SEARCH    = 8         # 탐색은 짧게, 프루닝/ES로 더 빨리 끝남
MAX_EPOCHS_FINAL     = 20         # 최종 재학습(네 스크립트 기본값 유지)

# ====== Optuna Study 영속화 설정 ======
STUDY_DB   = "sqlite:///optuna_tft.db"   # 현재 작업 폴더에 DB 파일 생성
STUDY_NAME = "tft_search"

# ====== 탐색 전용 축소 데이터셋(선택) ======
# True 로 두면 max_encoder_length / max_prediction_length 를 줄인 사본으로 탐색 속도 Up
USE_SEARCH_SHRINK   = True
SHRINK_ENCODER_LEN  = 120
SHRINK_PRED_LEN     = 12

# --- 탐색용 DataLoader 만들기 (축소 옵션 적용) ---
def build_search_loaders():
    if USE_SEARCH_SHRINK:
        search_kwargs = {**common_kwargs,
                         "max_encoder_length": SHRINK_ENCODER_LEN,
                         "max_prediction_length": SHRINK_PRED_LEN}
        search_training   = TimeSeriesDataSet(training_df, **search_kwargs)
        search_validation = TimeSeriesDataSet.from_dataset(
            search_training, validation_df, stop_randomization=True
        )
        search_train_loader = search_training.to_dataloader(
            train=True, batch_size=batch_size, num_workers=num_workers,
            pin_memory=True, persistent_workers=(num_workers > 0)
        )
        search_val_loader = search_validation.to_dataloader(
            train=False, batch_size=batch_size, num_workers=num_workers,
            pin_memory=True, persistent_workers=(num_workers > 0)
        )
        return search_train_loader, search_val_loader
    else:
        # 축소 미사용: 기존 로더 사용
        return train_loader, val_loader

search_train_loader, search_val_loader = build_search_loaders()

# ====== EarlyStopping 공통 설정 ======
early_stop_cfg = dict(monitor='val_loss', patience=2, mode='min', verbose=False)

# ====== trial 종료 시 베스트 파라미터 자동 저장(세션 끊겨도 복구용) ======
def on_trial_end(study: optuna.Study, trial: optuna.trial.FrozenTrial):
    if study.best_trial.number == trial.number:
        with open("best_params.json", "w") as f:
            json.dump(trial.params, f)

# ====== 프루너: 초기에 과감하게 컷 ======
pruner = optuna.pruners.SuccessiveHalvingPruner(
    min_resource=2,         # 최소 2 epoch 보고 가지치기 시작
    reduction_factor=4,     # 성능 나쁘면 과감히 컷
    min_early_stopping_rate=0
)

# ====== 목적함수: val_loss 최소화 ======
def objective(trial: optuna.Trial) -> float:
    # --- 하이퍼파라미터 검색공간 ---
    hidden_size            = trial.suggest_int("hidden_size", 16, 64, step=16)         # 16, 32, 48, 64
    hidden_continuous_size = trial.suggest_int("hidden_continuous_size", 8, 32, step=8)# 8, 16, 24, 32
    attention_head_size    = trial.suggest_int("attention_head_size", 1, 4)
    dropout                = trial.suggest_float("dropout", 0.05, 0.30)
    learning_rate          = trial.suggest_float("learning_rate", 1e-4, 1e-2, log=True)

    # --- 모델: 중앙값 한 개만 예측(연산량↓) ---
    model = TemporalFusionTransformer.from_dataset(
        training if not USE_SEARCH_SHRINK else search_train_loader.dataset,  # from_dataset은 dataset 객체를 요구
        learning_rate=learning_rate,
        hidden_size=hidden_size,
        attention_head_size=attention_head_size,
        dropout=dropout,
        hidden_continuous_size=hidden_continuous_size,
        output_size=7,
        loss=QuantileLoss(),
        log_interval=200,                   # 로깅 빈도 낮춤
        reduce_on_plateau_patience=2,
    )

    # --- 탐색용 Trainer: 절약 모드(검증/훈련 10%만), GPU 강제, 체크포인트 OFF ---
    pruning_cb = PyTorchLightningPruningCallback(trial, monitor="val_loss")
    early_stop = EarlyStopping(**early_stop_cfg)
    trainer_search = Trainer(
        max_epochs=MAX_EPOCHS_SEARCH,
        accelerator='gpu', devices=1,       # GPU 강제
        precision='bf16-mixed',
        gradient_clip_val=1.0,
        callbacks=[early_stop, pruning_cb],
        enable_checkpointing=False,         # I/O 절감
        logger=CSVLogger("logs", name=f"trial_{trial.number}"),
        enable_progress_bar=False,
        benchmark=True,                     # cudnn benchmark로 속도 ↑
        limit_train_batches=0.1,            # ★ 탐색: 학습 10%
        limit_val_batches=0.1,              # ★ 탐색: 검증 10%
    )

    t0 = time.time()
    trainer_search.fit(model, search_train_loader, search_val_loader)
    val = trainer_search.callback_metrics.get("val_loss")
    trial.set_user_attr("trial_minutes", (time.time() - t0) / 60)
    # 메모리 회수
    del model
    gc.collect(); torch.cuda.empty_cache()

    return float(val.item()) if val is not None else float("inf")

# ====== Study 생성(있으면 이어서) + 시간 예산 내 탐색 ======
study = optuna.create_study(
    direction="minimize",
    pruner=pruner,
    study_name=STUDY_NAME,
    storage=STUDY_DB,
    load_if_exists=True
)

study.optimize(
    objective,
    timeout=SEARCH_TIMEOUT_MIN * 60,     # 타임박스
    n_trials=N_TRIALS_UPPER_BOUND,      # 상한 — 실제로는 timeout에 의해 제한
    gc_after_trial=True,
    callbacks=[on_trial_end]
)

# ====== 베스트 파라미터 로드(파일 우선, 없으면 study에서) ======
if os.path.exists("best_params.json"):
    with open("best_params.json") as f:
        best_params = json.load(f)
else:
    best_params = study.best_trial.params

print("Best params (resumed if any):", best_params)

# ====== 최종 재학습: 원본 전체 데이터/배치로 ======
final_model = TemporalFusionTransformer.from_dataset(
    training,  # 원본 학습 데이터셋
    learning_rate=best_params["learning_rate"],
    hidden_size=best_params["hidden_size"],
    attention_head_size=best_params["attention_head_size"],
    dropout=best_params["dropout"],
    hidden_continuous_size=best_params["hidden_continuous_size"],
    output_size=7,
    loss=QuantileLoss(),
    log_interval=50,
    reduce_on_plateau_patience=3,
)

early_stop_final = EarlyStopping(monitor='val_loss', patience=3, mode='min', verbose=False)
ckpt = ModelCheckpoint(dirpath=CKPT_DIR, monitor='val_loss', save_top_k=1, mode='min')

trainer = Trainer(
    max_epochs=MAX_EPOCHS_FINAL,
    accelerator='gpu', devices=1,
    precision='bf16-mixed',
    gradient_clip_val=1.0,
    callbacks=[early_stop_final, ckpt],
    benchmark=True
)

trainer.fit(final_model, train_loader, val_loader)
best_path = ckpt.best_model_path
print(f"Best checkpoint: {best_path}")
"""

# -------------------------------
# 8-2) 모델 정의 & 학습
# -------------------------------
# 에폭 수 조정하기!
# Colab 유료 버전의 A100 GPU 사용 시 1 epoch 당 30분 정도 소요. 다른 GPU 사용 시 확인 바람.
max_epochs = 3

# 하이퍼파라미터 조정하기!
model = TemporalFusionTransformer.from_dataset(
    training,
    learning_rate=0.0026,
    hidden_size=48,
    attention_head_size=2,
    dropout=0.25,
    hidden_continuous_size=24,
    output_size=7,
    loss=QuantileLoss(),
    log_interval=50,
    reduce_on_plateau_patience=3,
)


if validation is None:
    # >>> CHANGED: 검증이 없으면 EarlyStopping 제거, 마지막만 저장
    ckpt = ModelCheckpoint(dirpath=CKPT_DIR, save_last=True)  # monitor=None
    callbacks = [ckpt]
else:
    early_stop = EarlyStopping(monitor='val_loss', patience=5, mode='min', verbose=True)
    ckpt = ModelCheckpoint(dirpath=CKPT_DIR, monitor='val_loss', save_top_k=1, mode='min')
    callbacks = [early_stop, ckpt]


trainer = Trainer(
    max_epochs=max_epochs,
    accelerator='auto',
    devices='auto',
    callbacks=callbacks,
    gradient_clip_val=0.1,
    precision='bf16-mixed'
    )

# val_loader가 없으면 train_loader만 넘김
if val_loader is None:
    trainer.fit(model, train_loader)
else:
    trainer.fit(model, train_loader, val_loader)

# 최종 경로 선택(검증X이면 last, 검증O면 best)
best_path = ckpt.last_model_path if validation is None else ckpt.best_model_path
print(f"Best checkpoint: {best_path}")

# 모델 실행 시 불필요
"""
# -------------------------------
# 9) 검증 예측 저장 (2019–2020)
# -------------------------------
best_model = TemporalFusionTransformer.load_from_checkpoint(best_path)
val_raw = best_model.predict(val_loader, mode="raw", return_index=True, return_y=True)

# (A) 예측값과 인덱스를 올바르게 정렬
predictions = val_raw.output[0].cpu().numpy()
true_values = val_raw.y[0].cpu().numpy()
index_df = val_raw.index

results_list = []
for i in range(len(index_df)):
  start_idx = index_df.iloc[i]['time_idx']
  series = index_df.iloc[i]['series_id']
  for h in range(max_prediction_length):
    pred_time_idx = start_idx + h
    results_list.append({
        "series_id": series,
        "time_idx": pred_time_idx,
        "y_pred": predictions[i, h, 3],
        "y_true": true_values[i, h]})

results_df = pd.DataFrame(results_list)

# (B) 저장: 시간 x 지점 형태의 피벗 테이블로 저장 (대회 쪽에서 제공해준 sample 데이터와 동일한 형태)
merged_df = validation_df.merge(results_df, on=["series_id", "time_idx"], how="inner")
pivoted_df = merged_df.pivot_table(index='ds', columns='series_id', values='y_pred', aggfunc='mean')
out_path_pivoted = os.path.join(OUTPUT_DIR, "predictions_pivoted_2019_2020.csv")
pivoted_df.to_csv(out_path_pivoted)

print(out_path_pivoted)
"""

# 모델 실행 시 불필요
"""
# 재연결
from google.colab import drive
drive.mount('/content/drive')
"""

# 모델 실행 시 불필요
"""
# 9-1) NSE, KGE 값 계산 및 real vs predict 그래프 출력

import matplotlib.pyplot as plt
# -------------------------------
# 성능 지표 함수
# -------------------------------
def nse(true, pred):
    true = np.asarray(true); pred = np.asarray(pred)
    return 1 - np.sum((true - pred) ** 2) / np.sum((true - np.mean(true)) ** 2)

def kge(true, pred):
    true = np.asarray(true); pred = np.asarray(pred)
    r = np.corrcoef(true, pred)[0, 1]
    alpha = np.std(pred) / np.std(true)
    beta  = np.mean(pred) / np.mean(true)
    return 1 - np.sqrt((r - 1)**2 + (alpha - 1)**2 + (beta - 1)**2)

# -------------------------------
# 경로 - 본인 환경에 맞게, 그리고 파일 이름(ex: 방금 예측한 파일이라 ~pivoted_2019_2020_5 로 함)도 수정 바람
# -------------------------------
PATH_PRED = "/content/outputs/predictions_pivoted_2019_2020.csv"
#PATH_TRUE = "/content/drive/MyDrive/Colab Notebooks/아쿠아리움/2014_2020_시계열_지하수_기상_train.csv"
PATH_TRUE = "/content/drive/MyDrive/Colab Notebooks/아쿠아리움/2014_2020_train_full_interpolated_filled_lag_plus.csv"

# 윗 줄의 PATH_TRUE 같은 경우 대회 측 제공 파일, 즉 시간대가 비어있는 경우가 있음.
# 이에 따라 특히 NSE 값이 +1에서 멀어짐. (분자가 '관측값 - 예측값'의 제곱이고, 그 값이 작아야 +1에 가까운데 관측값이 없으니...)

# 아랫 줄의 PATH_TRUE 같은 경우 빈 시간대를 보간했고, 이에 따라 윗 줄에 비해서는 NSE 값이 +1에 조금 더 가까워짐.
# 어느 것을 따라야할지는 모르겠지만, 실제 2021-2023년도를 예측할 때는 빈 시간대 없이 예측을 할 것이고, 그렇다면 후자가 좀 더 낫지 않나... -> 의견 제시 바람...!

# -------------------------------
# 예측 파일 로드/정리 (wide 형태 가정)
# - 날짜 컬럼명: 'ds' 또는 'ymd' 둘 다 대응
# - 사이트 컬럼은 모두 문자열로 통일 후 '_pred' 접미사 부여
# -------------------------------
pred_df = pd.read_csv(PATH_PRED, encoding='cp949')

date_col_pred = 'ds' if 'ds' in pred_df.columns else ('ymd' if 'ymd' in pred_df.columns else None)

pred_df[date_col_pred] = pd.to_datetime(pred_df[date_col_pred])
pred_df = pred_df.sort_values(date_col_pred).reset_index(drop=True)

# 예측의 사이트 컬럼 후보(= 날짜 컬럼 제외 전부)
pred_site_cols = [c for c in pred_df.columns if c != date_col_pred]
# 모든 컬럼명을 문자열로
pred_df.rename(columns={c: str(c) for c in pred_site_cols}, inplace=True)
pred_site_cols = [str(c) for c in pred_site_cols]

# '_pred' 접미사 부여
pred_df = pred_df.set_index(date_col_pred)
pred_df.columns = [f"{c}_pred" for c in pred_df.columns]

# -------------------------------
# 실제 파일 로드/정리 (long → wide)
# - 시간: 'ymd', 지점: 'code_new', 값: 'elev'
# - 분석 구간: 2019-01-01 ~ 2020-12-31
# - 사이트 컬럼은 문자열로 통일 후 '_true' 접미사 부여
# -------------------------------
true_df = pd.read_csv(PATH_TRUE, encoding='cp949')
true_df['ymd'] = pd.to_datetime(true_df['ymd'])
true_2019_2020 = true_df[(true_df['ymd'] >= "2019-01-01") & (true_df['ymd'] <= "2020-12-31")].copy()

# 피벗
true_pivot = true_2019_2020.pivot(index="ymd", columns="code_new", values="elev")
# 열 이름 문자열화
true_pivot.columns = [str(c) for c in true_pivot.columns]
# '_true' 접미사 부여
true_pivot = true_pivot.sort_index()
true_pivot.columns = [f"{c}_true" for c in true_pivot.columns]

# -------------------------------
# 인덱스(날짜) 기준 병합 (inner join)
# → 열 이름 충돌/접미사 문제 방지
# -------------------------------
merged = pred_df.merge(true_pivot, left_index=True, right_index=True, how="inner")

# -------------------------------
# 공통 사이트 식별 (양쪽 모두 존재하는 사이트만 평가)
# -------------------------------
pred_sites = [c[:-5] for c in merged.columns if c.endswith("_pred")]
true_sites = [c[:-5] for c in merged.columns if c.endswith("_true")]
common_sites = sorted(set(pred_sites).intersection(true_sites), key=lambda x: (len(x), x))

# -------------------------------
# 지점별 성능 평가
# -------------------------------
rows = []
for site in common_sites:
    y_true = merged[f"{site}_true"].astype(float)
    y_pred = merged[f"{site}_pred"].astype(float)

    # 동시 결측 제거
    mask = (~y_true.isna()) & (~y_pred.isna())
    if mask.sum() == 0:
        continue

    yt = y_true[mask].values
    yp = y_pred[mask].values

    rows.append({
        "site": site,
        "NSE": nse(yt, yp),
        "KGE": kge(yt, yp)
    })

results_df = pd.DataFrame(rows).set_index("site").sort_index()
display(results_df)

# -------------------------------
# 시각화 -> common_sites 안의 수를 바꿔서 지점 별로 바꾸세요!!!
# -------------------------------
if len(common_sites) > 0:
    site0 = common_sites[5] # 여기!!!
    plt.figure(figsize=(12,5))
    plt.plot(merged.index, merged[f"{site0}_true"], label="real")
    plt.plot(merged.index, merged[f"{site0}_pred"], label="predict")
    plt.title(f"place no.{site0} — real vs predict (2019–2020)")
    plt.xlabel("time")
    plt.ylabel("elev")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()

# -------------------------------
# (옵션) 모든 지점 그래프 저장
# -------------------------------
for site in common_sites:
    fig = plt.figure(figsize=(12,5))
    plt.plot(merged.index, merged[f"{site}_true"], label="real")
    plt.plot(merged.index, merged[f"{site}_pred"], label="predict")
    plt.title(f"place no.{site} — real vs predict (2019–2020)")
    plt.xlabel("time")
    plt.ylabel("elev")
    plt.legend(); plt.grid(True, alpha=0.3)
    fig.savefig(f"compare_site_{site}.png", dpi=150, bbox_inches="tight")
    plt.close(fig)
"""

# 모델 실행 시 불필요
"""
# 9-2) 전체 평균 성능 지표

mean_metrics = results_df[['NSE','KGE']].mean()
print("전체 평균 성능 지표:")
print(mean_metrics)
"""

# -------------------------------
# 10) 테스트 입력 로드 & 오토리그레시브 예측 (타깃 래그 유지 모델)
# -------------------------------

# 0) 준비: 학습 시 사용한 객체들
# - training: 학습 TimeSeriesDataSet
# - training_df: 2014~2020 full train df (normalize_columns/정렬/열구성 동일)
# - best_model: ckpt에서 로드한 TFT
# - static_cols, num_cols, cat_cols, known_future_real, max_encoder_length, max_prediction_length, batch_size 등은 학습 파트와 동일
best_model = TemporalFusionTransformer.load_from_checkpoint(best_path)

# 1) 원천 데이터 로드/정규화/머지
train = pd.read_csv(PATH_TRAIN, encoding='cp949')
site  = pd.read_csv(PATH_SITE,  encoding='cp949')
test  = pd.read_csv(PATH_TEST_INPUTS, encoding='cp949')

for df_ in (train, site, test):
    df_.columns = df_.columns.str.replace('.', '_', regex=False)

train = normalize_columns(train)
test  = normalize_columns(test)

site_id_cols = [c for c in site.columns if c.lower() in ['code','code_new','site','site_id','station']]
if not site_id_cols:
    raise ValueError('정적 지점 파일에서 식별자 컬럼을 찾을 수 없습니다.')
site = site.rename(columns={site_id_cols[0]: 'series_id'})

# 정적 머지 & 정렬
train = train.merge(site, on='series_id', how='left')
test  = test.merge(site,  on='series_id', how='left')

train = train.sort_values(['series_id','ds']).reset_index(drop=True)
test  = test.sort_values(['series_id','ds']).reset_index(drop=True)

# time_idx
train['time_idx'] = train.groupby('series_id').cumcount()
# test의 time_idx는 train 마지막 index에 이어 붙이기
last_idx = train.groupby('series_id')['time_idx'].max()
test['offset']   = test['series_id'].map(last_idx).fillna(-1).astype(int)
test['time_idx'] = test.groupby('series_id').cumcount() + test['offset'] + 1
test = test.drop(columns=['offset'])

# 시간 관련 known-future
for col, fn in [('hour', lambda s: s.dt.hour),
                ('dow',  lambda s: s.dt.dayofweek),
                ('month',lambda s: s.dt.month)]:
    if col not in train.columns:
        train[col] = fn(train['ds'])
    if col not in test.columns:   # 안전상 재확인
        test[col] = fn(test['ds'])

# ---------- 핵심 보조함수: 타깃 래그 재계산 ----------
LAGS = [168, 336, 504]

def recompute_target_lags(df: pd.DataFrame) -> pd.DataFrame:
    """
    df: (단일 series_id 또는 다중 series_id 모두 허용)
    y가 관측/예측으로 섞여 있는 상태에서 지점별로 타깃 래그와 prefill 플래그를 재계산.
    """
    out = df.copy()
    # 지점별-시간 순서 보장 (time_idx가 확실하면 그걸 우선 사용)
    sort_keys = ['series_id', 'time_idx'] if 'time_idx' in out.columns else ['series_id', 'ds']
    out = out.sort_values(sort_keys).reset_index(drop=True)

    # 지점별로 그룹-shift → 절대 다른 지점으로 값이 밀려 들어가지 않음
    g = out.groupby('series_id', sort=False, observed=True)

    for lag in LAGS:
        lag_col = f'elev_lag_{lag}h'
        pre_col = f'is_prefill_{lag}h'

        out[lag_col] = g['y'].shift(lag)               # 그룹별 shift
        out[pre_col] = out[lag_col].isna().astype(float)  # 래그가 비면 1, 아니면 0

    return out

# 강수량 컬럼명 (데이터 그대로 씁니다)
RAIN_COL = '강수량(mm)'

def recompute_sum24h(df: pd.DataFrame) -> pd.DataFrame:
    """
    series_id별로 24시간 누적 강수량(sum_of_rain_24h) 재계산.
    - strict: window=24, min_periods=24 (진짜 24시간 누적만)
    - loose : window=24, min_periods=1  (부족 시간 보정용)
    첫 24시간에는 strict가 NaN이므로 loose로 채우고,
    그 구간을 is_first24h_sum_24h=1로 표시.
    """
    out = df.copy()
    sort_keys = ['series_id', 'time_idx'] if 'time_idx' in out.columns else ['series_id', 'ds']
    out = out.sort_values(sort_keys).reset_index(drop=True)

    g = out.groupby('series_id', sort=False, observed=True)
    strict = g[RAIN_COL].rolling(window=24, min_periods=24).sum().reset_index(level=0, drop=True)
    loose  = g[RAIN_COL].rolling(window=24, min_periods=1).sum().reset_index(level=0, drop=True)

    # 플래그: strict가 비는(=진짜 첫 24시간) 구간
    first24 = strict.isna().astype(float)

    out['sum_of_rain_24h'] = strict.fillna(loose).astype(float)
    out['is_first24h_sum_24h'] = first24

    # 혹시 남은 NaN은 0으로
    out['sum_of_rain_24h'] = out['sum_of_rain_24h'].fillna(0.0)
    out['is_first24h_sum_24h'] = out['is_first24h_sum_24h'].fillna(0.0)

    return out

# test.info() -> 모델 실행 시 불필요

# ---------- 시리즈별 오토리그레시브 루프 ----------
pred_rows = []  # (series_id, time_idx, y_pred)

unique_series = test['series_id'].unique()
print(f"Series count: {len(unique_series)}")

# encoder 컨텍스트는 최대 래그까지 필요(여기선 504h). 안전하게 504h 사용.
CONTEXT_H = max_encoder_length + max(LAGS)

for sid in unique_series:
    test_s = test[test['series_id'] == sid].copy()
    train_s = train[train['series_id'] == sid].copy()

    if train_s.empty or test_s.empty:
        continue

    # 1) 컨텍스트: 2020년 말 기준 마지막 CONTEXT_H시간 확보 (부족하면 가능한 만큼)
    ctx_tail = train_s.tail(CONTEXT_H).copy()

    # 2) 베이스 프레임 구성: 컨텍스트(관측 y 포함) + 테스트(미래 y = NaN)
    base = pd.concat([ctx_tail, test_s], ignore_index=True)
    if 'y' not in base.columns:
        base['y'] = np.nan

    # 🔧 플래그/지표 NaN 안전 채움 (학습 스키마에 있는 실수형 지표들은 NaN 금지)
    fill_zero_cols = [
        'is_precipitation_missing',
        'is_first24h_sum_24h',
        'is_prefill_168h', 'is_prefill_336h', 'is_prefill_504h'  # 곧 재계산되지만 일단 0으로
    ]
    for c in fill_zero_cols:
        if c in base.columns:
            base[c] = base[c].fillna(0.0).astype(float)

    # (주의) 학습에서 사용한 모든 피처 컬럼이 존재해야 함.
    # known-future는 채워졌고, 정적/기상/강수/기온 등 외생 변수는 test 파일에 들어있어야 합니다.
    # 타깃 래그는 아래에서 반복 계산로 채웁니다.
    base = base.sort_values('ds').reset_index(drop=True)

    # 예측은 24시간씩 끊어서 (max_prediction_length) 진행
    # 시작 인덱스: 테스트 첫 행의 위치
    start_idx = ctx_tail.shape[0]
    end_idx   = base.shape[0]

    total_h = end_idx - start_idx
    last_t = None
    stalled_steps = 0

    t = start_idx
    while t < end_idx:
        # 남은 시간이 24 미만이면 마지막 블록을 만들도록 시작점 당김
        remain = end_idx - t
        if remain < max_prediction_length:
          t = end_idx - max_prediction_length

        # 진행률/상태 로그 (지점별 1~2초에 한 번 정도 보이게)
        if last_t is None or (t - last_t) >= max_prediction_length*4:
            done_h = t - start_idx
            print(f"[series {sid}] progress: {done_h}/{total_h} hours "f"({done_h/total_h:.1%}), t={t}, end={end_idx}")
            last_t = t

        # 1) 타깃 래그
        base = recompute_target_lags(base)

        # 2) 24h 누적 강수량
        base = recompute_sum24h(base)

        # 3) 안전 보정(남아 있으면 0으로)
        for c in ['is_precipitation_missing', 'is_first24h_sum_24h',
                  'is_prefill_168h', 'is_prefill_336h', 'is_prefill_504h',
                  'sum_of_rain_24h']:
            if c in base.columns:
                base[c] = base[c].fillna(0.0).astype(float)

        # 이번 스텝 예측 범위
        t_end = min(t + max_prediction_length, end_idx)
        enc_start = max(0, t - max_encoder_length)
        use_block = base.iloc[enc_start:t_end].copy()

        # 디코더 시작 time_idx
        dec_start_tidx = base.iloc[t]['time_idx']

        # ⚙️ 디코더(y=NaN)만 임시 채움: 최근 관측/예측값으로 ffill, 그래도 비면 0
        use_block_filled = use_block.copy()
        dec_mask = use_block_filled['time_idx'] >= dec_start_tidx
        use_block_filled.loc[dec_mask, 'y'] = (
            use_block_filled.loc[dec_mask, 'y'].ffill()
        )
        use_block_filled['y'] = use_block_filled['y'].fillna(0.0)

        # TimeSeriesDataSet.from_dataset으로 인코딩 규칙 재사용
        block_ds = TimeSeriesDataSet.from_dataset(
            training,
            use_block_filled,
            predict=True,
            stop_randomization=True,
            allow_missing_timesteps=True
        )
        block_loader = block_ds.to_dataloader(train=False, batch_size=batch_size, num_workers=0)

        raw = best_model.predict(block_loader, mode="raw", return_index=True)
        # 중앙(0.5) 분위수 인덱스: output_size=7 -> 0, 0.1, 0.2, 0.3, 0.5, 0.7, 0.9 라면
        # 학습 코드에서 3을 사용하셨는데, 일반적으로 0.5는 보통 중간쯤입니다.
        # 모델 설정에 따라 다를 수 있으니 기존 인덱스(3) 유지
        yhat = raw.output.prediction.cpu().numpy()  # [N, H, 7]
        idx  = raw.index

        # raw.index의 각 샘플 시작 time_idx에 대해 H개 예측
        for i in range(len(idx)):
            start_time_idx = idx.iloc[i]['time_idx']
            sid_i          = idx.iloc[i]['series_id']
            for h in range(max_prediction_length):
                pred_time_idx = start_time_idx + h
                # 현재 배치가 목표 구간 안에 있을 때만 반영
                # (이번 스텝 타깃 구간은 [t, t_end))
                # use_block는 enc_start 기준 time_idx 연속이라 base의 time_idx와 동일 매핑
                mask = (base['time_idx'] == pred_time_idx)
                if mask.any():
                    # 예측값
                    pred_val = float(yhat[i, h, 3])
                    # 1) 결과 수집
                    pred_rows.append((sid_i, pred_time_idx, pred_val))
                    # 2) base['y'] 채워 넣어 다음 스텝의 래그 계산에 사용
                    base.loc[mask, 'y'] = pred_val

        # 예측 루프/누적 끝난 뒤
        if t_end == end_idx:
          print(f"[series {sid}] finished final 24h block.")
          break

        # 다음 구간으로 이동
        t = t_end

# 3) 예측 결과 DataFrame 정리
pred_df = pd.DataFrame(pred_rows, columns=['series_id','time_idx','y_pred']).drop_duplicates(['series_id','time_idx'])
# 테스트 기간(2021–2023)에 해당하는 행만 남기기
test_key = test[['series_id','time_idx','ds']].copy()
test_out = test_key.merge(pred_df, on=['series_id','time_idx'], how='inner')

# 피벗(대회 제출 포맷 유사)
pivoted = test_out.pivot_table(index='ds', columns='series_id', values='y_pred', aggfunc='mean').sort_index()
out_path = os.path.join(OUTPUT_DIR, "predictions_pivoted_2021_2023.csv")
pivoted.to_csv(out_path, encoding='cp949')
print("Saved:", out_path)